### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by coding-sunshine** [oxygen-cms/application#1]
I wanted to explore more but can't install please if you can provide basic instruction

**Comment by neon64** [comment]
At the moment the easiest way is to clone the repository and then run `composer install`. You'll need a PHP web server and set the document root to the 'public' folder. I'm only running it myself for 2 different clients so I've forgotten if there is any more steps. You might need to seed the database.

The main administration interface can be accessed at the `yourwebsite.com/oxygen`.

**Comment by coding-sunshine** [comment]
I tried your installer but its giving me following error:

Any idea how to resolve this :(

```
PHP Parse error: parse error, expecting `"identifier (T_STRING)"' or `"variable (T_VARIABLE)"' or `'{'' or `'$'' in /Applications/MAMP/htdocs/laravel/exp/oxygen/artisan on line 31 Error "Uncaught exception 'RuntimeException' with message 'Error Output: PHP Parse error: parse error, expecting `"identifier (T_STRING)"' or `"variable (T_VARIABLE)"' or `'{'' or `'$'' in /Applications/MAMP/htdocs/laravel/exp/oxygen/artisan on line 31 ' in /Applications/MAMP/htdocs/laravel/exp/oxygen/oxygenInstall/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php:177 Stack trace: #0 /Applications/MAMP/htdocs/laravel/exp/oxygen/oxygenInstall/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php(91): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event)) #1 /Applications/MAMP/htdocs/laravel/exp/oxygen/oxygenInstall/vendor/composer/composer/src/Composer/Installer.php(364): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', true) #2 /Applications/MAMP/htdocs/laravel/exp/oxygen/oxygenInstall/vendor/composer/composer/src/Composer/Command/UpdateCommand.php(140): Composer\Installer->run() #3 /Applications/MAMP/htdocs/laravel/" in file /Applications/MAMP/htdocs/laravel/exp/oxygen/oxygenInstall/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php on line 177 (Type: Fatal)
```

**Comment by coding-sunshine** [comment]
and when I tried composer install everything ran fine but when I open 
mywebsite.com/
or 
mywebsite.com/oxygen

it gives me following error :

```
PreferenceNotFoundException in DatabaseLoader.php line 47: Preference Key appearance.themes Not Found In Database

```

**Comment by neon64** [comment]
When you say 'my installer' do you mean the graphical one at 'oxygen-cms/installer' or composer. The graphical one is bound to be buggy and outdated so I wouldn't use that. 

The `PreferenceNotFoundException` is a hint that the database hasn't been seeded yet. To do that run `php artisan migrate:packages`.

Also have you entered the database info into `config/database.php`?

I'm sorry that the install process is so difficult at the moment. I'm excited that some other people are looking at using the CMS so I will make sure to improve it soon.

**Comment by coding-sunshine** [comment]
sorry but even `php artisan migrate:packages` didn't work.
I have my confif/database.php ready but when I try to migrate you packages it gives me following errors:

```
[Doctrine\DBAL\Exception\TableNotFoundException]                                                                                         
  An exception occurred while executing 'INSERT INTO preferences (`key`, contents) VALUES (?, ?)' with params ["appearance.admin", "[]"]:  
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'oxygen.preferences' doesn't exist                                             

 [Doctrine\DBAL\Driver\PDOException]                                                           
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'oxygen.preferences' doesn't exist  

  [PDOException]                                                                                
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'oxygen.preferences' doesn't exist

```

Its not able to find the preferences table and even i couldn't locate it in migrations.

I haven't used your CMS yet as not able to install it but I have gone through the code and kind of like the way it is working, I was planning to build something similar for my projects and then came across yours and liked the way it was structured, similar to what I had in my mind so thought of using the same and improve upon it to fit my requirements rather than building one from scratch.

It would be great help if you can help me to set up at initial stage :)

**Comment by neon64** [comment]
After trying to install it myself I've realised just how difficult I've made it. I'm working now on making proper installation instructions but for now there's a few commands that must be run:

Before `php artisan migrate:packages` you need `php artisan doctrine:schema:update` (ie: must actually create database structure before trying to insert content into it)

You'll also need to run `php artisan vendor:publish --tag=public --force` to get the awesome CSS/JS resources.

By that stage you should be able to access `yourwebsite.com/oxygen` at get a login page.

However in a major oversight I have realised there is no way to create a user without a user account (not even via Terminal)

I'm working on adding some `artisan` commands (`make:user` and `make:group`) that will do that. Until then, you can't login!!!!

**Comment by neon64** [comment]
I've created the console commands and also added installation instructions to the [README](https://github.com/oxygen-cms/application/blob/master/readme.md).

If you run `composer update` then you'll be able to run `php artisan make:group YourGroupName` and then `php artisan make:user`.

Let me know if you have any more problems with installation and/or questions about extending Oxygen to suit your needs.

**Comment by coding-sunshine** [comment]
Thanks,
I will try this today.

**Comment by coding-sunshine** [comment]
Thanks very much, I was able to install it now easily :)
I will try your CMS now.
